name: Create or Update Pull Request on Branch Creation

on:
  workflow_call:

jobs:
  create-or-update-pull-request:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get commit messages
      id: get_commits
      run: |
        git log origin/master..HEAD --pretty=format:"%h %s" > commit_messages.txt
        cat commit_messages.txt

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt-get update
        sudo apt-get install gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Get existing PR number
      id: get_existing_pr
      run: |
        pr_number=$(gh pr list --head ${{ github.ref }} --json number --jq '.[0].number')
        echo "::set-output name=pr_number::$pr_number"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get next PR number if no existing PR
      if: steps.get_existing_pr.outputs.pr_number == ''
      id: get_next_pr_number
      run: |
        next_pr_number=$(($(gh pr list --json number --jq '.[].number' | sort -nr | head -n1) + 1))
        echo "::set-output name=pr_number::$next_pr_number"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create or Update Pull Request
      if: steps.get_existing_pr.outputs.pr_number == ''
      id: create_pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        base: master
        title: '${{ github.ref }} - Automatic Pull Request #${{ steps.get_next_pr_number.outputs.pr_number }}'
        body: |
          This pull request is automatically created or updated when a new branch is pushed.
          - Branch: ${{ github.ref }}

          ## Commits:
          $(cat commit_messages.txt)
        committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        delete-branch: false
        branch-suffix: timestamp
        update-existing-pr: true

    - name: Update Pull Request
      if: steps.get_existing_pr.outputs.pr_number != ''
      run: |
        gh pr edit ${{ steps.get_existing_pr.outputs.pr_number }} --body "$(cat commit_messages.txt)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
